"use client";
import "../app/global.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "react-toastify/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { Provider } from "react-redux";
import store from "./store";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>
          <Header />
          <main className="p-5">{children}</main>
          <Footer />
          <ToastContainer />
        </body>
      </html>
    </Provider>
  );
}
