"use client";
import "../app/global.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "react-toastify/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { Provider } from "react-redux";
import store from "./store";
import { Zilla_Slab } from "next/font/google";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

const playfair = Zilla_Slab({
  weight: "300",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>
          {modal}
          <Header />
          <main className={`p-5 pt-16  mx-1 xl:mx-36   ${playfair.className}`}>
            {children}
          </main>
          <Footer />
          <ToastContainer />
        </body>
      </html>
    </Provider>
  );
}
